apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  DB_NAME: postgres
  DB_USER: postgres
  DB_HOST: project3-postgresql
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
stringData:
  DB_PASSWORD: MCAFvzZ3Dj